### ISSUE TITLE
BUG: LivePVTableModel polling isn't stopped before deletion when main window is closed 

### ISSUE THREAD

**Issue by shilorigins** [pcdshub/superscore#88]
## Current Behavior

Closing the main window while a tab with a `LivePVTableModel` is open causes this error:
```
QThread: Destroyed while thread is still running
Aborted (core dumped)
```
## Expected Behavior

Tabs with `LivePVTableModel` should stop their polling threads before closing to ensure clean shutdown.
## Steps to Reproduce (for bugs)

1. `superscore ui`
2. Open collection builder page e.g. File -> New -> Collection
3. Close main window by clicking top-right `X` 

## Suggested Solution

I've tried implementing `closeEvent` in `window.py::Window` to close all tabs in tab widget, but this event doesn't seem to trigger.  `closeEvent` is also implemented in the collection builder page, but closing the main window doesn't seem to send close events to all widgets.

There are flags like `DeleteOnClose` and signals like `destroyed` that may be more reliable, but this reliability comes at bluntness, and closing seems like the preferred way to handle clean up.

**Comment by tangkong** [comment]
I think overriding closeEvent in `window.py::Window` works, or at least it does for me.  That's probably the place to call this functionality.  

these close events are supposed to be propagated.  Maybe the tabwidget isn't parented / parenting as thoroughly as we need

**Comment by tangkong** [comment]
Seems we should have the main window close its "children" https://stackoverflow.com/questions/4456252/qt-multiple-windows-in-a-parent-child-chain-parent-does-not-close-children

**Comment by tangkong** [comment]
This should work as `window.py::Window.closeEvent()`:
```python
    def closeEvent(self, a0: QCloseEvent) -> None:
        print('closing main window')
        for i in range(self.tab_widget.count()):
            self.remove_tab(0)
        return super().closeEvent(a0)
```

**Comment by shilorigins** [comment]
> This should work as `window.py::Window.closeEvent()`:
> 
> ```python
>     def closeEvent(self, a0: QCloseEvent) -> None:
>         print('closing main window')
>         for i in range(self.tab_widget.count()):
>             self.remove_tab(0)
>         return super().closeEvent(a0)
> ```

That's exactly what I did, but mine hasn't been working.  I'll poke around some more.

**Comment by shilorigins** [comment]
> > This should work as `window.py::Window.closeEvent()`:
> > ```python
> >     def closeEvent(self, a0: QCloseEvent) -> None:
> >         print('closing main window')
> >         for i in range(self.tab_widget.count()):
> >             self.remove_tab(0)
> >         return super().closeEvent(a0)
> > ```
> 
> That's exactly what I did, but mine hasn't been working. I'll poke around some more.

X that, I had a dumb bug in my loop. I've got it working now.
