### ISSUE TITLE
Write `Entry` comparison method

### ISSUE THREAD

**Issue by tangkong** [pcdshub/superscore#9]

**Comment by shilorigins** [comment]
`@dataclass` produces a default `__eq__` that treats instances of the dataclass as a tuple of their attributes.  This seems reasonable, so we may not need to define our own comparison method.  Even if we use the default, I'll add test cases to ensure comparisons work as we expect them to.

**Comment by tangkong** [comment]
I was thinking more about if we wanted to show the user the difference between two `Entry`'s, as in the GUI.  The `__eq__` method should return a bool but it won't tell us where the objects differ right?

**Comment by shilorigins** [comment]
Ah, I see what you mean.
